# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagesection_homeproductrelatedlink_indexlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='sectionClassName',
            field=models.SlugField(default='home-page-section', help_text='no spaces', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='sectionTitle',
            field=models.CharField(default='Web Development', max_length=50),
        ),
    ]
