# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-02 21:11
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180202_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='streamBody',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('markup', wagtail.wagtailcore.blocks.RawHTMLBlock())], null=True),
        ),
    ]
