# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-03 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0012_copy_image_permissions_to_collections'),
        ('home', '0006_auto_20180203_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default='Omar Rahman', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.CharField(default='Web Developer, Designer, Illustrator', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
