# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180203_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='orientation',
            field=models.CharField(choices=[('left', 'LEFT'), ('right', 'RIGHT'), ('centre', 'CENTRE')], default='left', max_length=50),
        ),
    ]
