# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-03 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagesection_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesection',
            name='sectionTitle',
        ),
    ]
