# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-06 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180206_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippetclass',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepagesection',
            name='advert',
        ),
        migrations.DeleteModel(
            name='SnippetClass',
        ),
    ]
