# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180206_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeproductrelatedlink',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
