# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180303_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='uploaded_by_user',
        ),
        migrations.AlterUniqueTogether(
            name='customrendition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='customrendition',
            name='image',
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.CustomImage'),
        ),
        migrations.DeleteModel(
            name='CustomImage',
        ),
        migrations.DeleteModel(
            name='CustomRendition',
        ),
    ]
