# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180303_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rel_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.HomeProductRelatedLink'),
        ),
    ]
