# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 03:30
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_homepage_rel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='customMarkup',
            field=wagtail.wagtailcore.fields.StreamField([('markup', wagtail.wagtailcore.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
