# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customimage_photo_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customimage',
            old_name='photo_credit',
            new_name='photographer',
        ),
        migrations.AddField(
            model_name='customimage',
            name='display_credit',
            field=models.BooleanField(default=False, help_text='Hides recipe from main index view (aka: list view)'),
        ),
        migrations.AddField(
            model_name='customimage',
            name='photo_credit_link',
            field=models.URLField(blank=True, verbose_name='External link'),
        ),
    ]
