# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180305_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customimage',
            name='display_credit',
            field=models.BooleanField(default=False, help_text='redners photographer name as link (if available)'),
        ),
    ]
