# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
                ('amount', models.CharField(help_text='Amount', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='subrecipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
