# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipeprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeprofile',
            old_name='title',
            new_name='name_of_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='main_image',
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='amount',
            field=models.CharField(default=datetime.datetime(2018, 2, 9, 3, 35, 57, 248108, tzinfo=utc), help_text='Link title', max_length=255),
            preserve_default=False,
        ),
    ]
