# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20180209_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeprofile',
            name='amount',
            field=models.CharField(blank=True, help_text='Link title', max_length=255),
        ),
    ]
