# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20180209_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='subrecipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
