# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20180209_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredientthings',
        ),
    ]
