# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_ingredientthings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='amount_of',
            field=models.CharField(blank=True, help_text='Amount', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subrecipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
    ]
