# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipeprofile_thisorthat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='subrecipe',
            field=models.ForeignKey(blank=True, help_text='True', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
    ]
