# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20180210_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeprofile',
            old_name='thisOrThat',
            new_name='this_or_next',
        ),
    ]
