# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20180210_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='subrecipe_only',
            field=models.BooleanField(default=False, help_text='Hides recipe from main index view (aka: list view)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subrecipe',
            field=models.ForeignKey(blank=True, help_text='Links to another recipe page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
    ]
