# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 18:55
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20180210_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeprofile',
            old_name='link_page',
            new_name='recipe_in_recipe_page',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='link_external',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='name_of_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='this_or_next',
        ),
        migrations.AlterField(
            model_name='recipeprofile',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in_recipe', to='recipes.Recipe'),
        ),
    ]
