# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20180210_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeprofile',
            name='recipe_in_recipe_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.Recipe'),
        ),
    ]
