# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_auto_20180210_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeprofile',
            name='link_external',
            field=models.URLField(blank=True, verbose_name='External link'),
        ),
    ]
