# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('recipes', '0022_auto_20180210_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInRecipeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_in_recipe', to='recipes.Recipe')),
                ('recipe_in_recipe_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.Recipe')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recipeprofile',
            name='recipe_in_recipe_page',
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='amount',
            field=models.CharField(blank=True, help_text="Amount: e.g. '1 2/3 cups'", max_length=255),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='name_of_ingredient',
            field=models.CharField(default='apples', help_text="Ingredient: e.g. 'Flour' ", max_length=255),
        ),
        migrations.AddField(
            model_name='recipeprofile',
            name='this_or_next',
            field=models.BooleanField(default=False, help_text="Adds 'Or' between this and next ingredient"),
        ),
        migrations.AlterField(
            model_name='recipeprofile',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_items', to='recipes.Recipe'),
        ),
    ]
