# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-11 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20180211_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='subrecipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='subrecipe',
            field=models.ForeignKey(blank=True, help_text='Links to another recipe page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Recipe'),
        ),
    ]
