# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('recipes', '0026_recipeindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='recipeinrecipeprofile',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading text for subrecipe (optional)', max_length=255, null=True),
        ),
    ]
