# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-12 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_auto_20180212_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_recipe',
            field=models.BooleanField(default=False, help_text='Shows recipe in featured recipe section'),
        ),
    ]
