# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_remove_recipe_subrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
