# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:42
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_recipe_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='blurb',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=1200),
        ),
    ]
