# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_recipe_blurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='amount_of',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_name',
        ),
    ]
