# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0032_auto_20180213_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dairy_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
