# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_auto_20180213_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dairy_free',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegetarian',
        ),
    ]
